###
GET http://localhost:8000/api/events

###
GET http://localhost:8000/api/rsvp

###
POST http://localhost:8000/api/rsvp
Content-Type: application/json

{
  "event_id": 1,
  "name": "João",
  "email": "joao@email.com"
}

###
POST http://localhost:8000/api/events
Content-Type: application/json

{
  "title": "Evento 1",
  "date": "2023-10-01",
}